# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    timeout-minutes: 15  # Общий таймаут для всего job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        timeout-minutes: 3  # Таймаут для установки Swift
        with:
          swift-version: "5.9"
          
      - name: Verify Swift Installation
        run: swift --version  # Явная проверка установки

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          swift build -v  # Подробный вывод сборки
        timeout-minutes: 5

      - name: Run Tests
        run: |
          swift test --parallel --enable-test-discovery -v --filter ".*"  # Подробный вывод тестов
        timeout-minutes: 7
